version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: reservas
    ports:
      - "5432:5432"
    volumes:
      - reservas_postgres:/var/lib/postgresql/data

volumes:
  reservas_postgres: